### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Hoa0** [bommezijn/frontend-applications#3]
### Welke onderdeel
[link to live demo on github pagesl](https://frontend-applications-eight.vercel.app/#two)

### Probleem
- [x]  website staat online, alleen is er nog geen Datavisualisatie te zien.
- [x] er staan nog dummy data erop en een lijst met acteurs namen
- [x] website is nog onduidelijk van wat het wilt laten zien

### Voorstel
- je hebt nog ander halve dag te gaan
- [x] code pushen naar de main

**Comment by bommezijn** [comment]
Thanks, Zal mijn environments updaten zodat het zichtbaar is

**Comment by bommezijn** [comment]
Closing issue as I solved the problems
