### ISSUE TITLE
Peer review - Wiki

### ISSUE THREAD

**Issue by AllyssaA** [bommezijn/frontend-applications#4]
### Welke onderdeel
[wiki](https://github.com/bommezijn/frontend-applications/wiki)

### Probleem
Naar mijn gevoel missen er een paar details in de wiki.

### Voorstel

- [x] Frameworks
Staan een paar linkjes bij welke je hebt gebruikt en hebt onderzocht. 
Misschien kan je er wat over schrijven over de verschillende frameworks die je hebt onderzocht. 
Wat de voor en/of nadelen zijn van deze frameworks, en misschien een korte uitleg over de keuze van de framework waarmee je hebt gewerkt en je ervaringen hiermee.

- [x] Journal
In je journal staan nog niet alle dagen gelogd. Ik weet dat je dagelijks aantekeningen maakt, dus als je  die samenvat en bij de juiste dagen toevoegd, moet het wel goedkomen 😊

**Comment by bommezijn** [comment]
Thanks. Ik zal de wiki verbeteren op basis van de feedback die ik heb gekregen.

**Comment by bommezijn** [comment]
Zal de frameworks niet meer beschrijven omdat we hier geen aandacht aan zullen besteden.
